### ISSUE TITLE
Notify new users of the feed

### ISSUE THREAD

**Issue by AvivRubys** [AvivRubys/bluesky-hebrew-feed#6]
Hebrew feed helps with the discoverability problem of a new social network. But how do we make sure the feed itself is discoverable, when new users don't know about feeds?
We could add a bot that comments on hebrew posts made by new users, and introduces them to the feed, also letting them know they appear in it (as menioned in #4 there's no opt-out mechanism right now, but we could add one if needed).

Design principles:
* Separate the bot entity from myself or other contributors - create a new account for this
* Only comment on users' first post in hebrew (the same criteria that the hebrew noobs feed uses)
* Prevent these repetative bot messages from appearing in any feeds we control
* The comment should let the user know
  * The feeds are there for them to consume (and how to do so)
  * Their messages automatically appear in the feed
  * Who to turn to for issues

More discussion [here](https://bsky.app/profile/avivr.dev/post/3k4bqra4qay27)

**Comment by AvivRubys** [comment]
Closed by #13

**Comment by avipars** [comment]
This becomes spammy and annoying

**Comment by AvivRubys** [comment]
@avipars Only hits every person one time, and feedback has been good that it helps people find other hebrew speakers, so I'm keeping it :)
