### ISSUE TITLE
Feed statistics

### ISSUE THREAD

**Issue by AvivRubys** [AvivRubys/bluesky-hebrew-feed#8]
I'd like to know some basic statistics about the feed, such as:
* Active users e.g. DAU/WAU/MAU
* Number of posts
* Posts per hour/day
* Feed views per hour/day

**Comment by AvivRubys** [comment]
We could do a few things here:
* Prometheus/grafana - literally designed for this, but feels a bit heavy-handed to start installing and configuring these for just one small server
* Log based stats, using something like goaccess.io or other log analyzers
* Something custom - shouldn't be that difficult to throw some stats into sqlite and query them, and visualize with chartjs

**Comment by Kelrak** [comment]
Grafana labs have a free tier it seems https://grafana.com/pricing/

**Comment by AvivRubys** [comment]
@Kelrak 
That's actually awesome! If we combine that with a simple source supported by grafana, that removes a decent piece of complexity from this setup. I guess this leaves the question - what's the simplest lightweight data store supported by grafana?

**Comment by Kelrak** [comment]
So their solution is to use a thing called grafan agent that is essentially a really small scale prometheus that doesn't have local storage and just ships the metrics to their backend

**Comment by AvivRubys** [comment]
That sounds decent actually, I might try that (or if you want to?)

**Comment by AvivRubys** [comment]
Mostly resolved through grafana agent
